name: auto_pigeon
description: AutoPigeon extended Pigeon to support configuring the directory for generation.
version: 1.0.1
homepage: https://github.com/eitanliu/auto_pigeon
repository: https://github.com/eitanliu/auto_pigeon

executables:
  auto_pigeon:

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  args: ^2.0.0
  path: ^1.0.0
  collection: ^1.0.0
  pigeon: '>=12.0.0 <20.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.0.0
